### ISSUE TITLE
go test badge not working

### ISSUE THREAD

**Issue by roncewind** [Senzing/template-go#108]
in our list of badges we have one for go-test.yaml, but it's not working in this repo or others I checked:

in the readme.md we have:

```[![go-test.yaml](https://github.com/Senzing/template-go/actions/workflows/go-test.yaml/badge.svg)](https://github.com/Senzing/template-go/actions/workflows/go-test.yaml)```

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/template-go/pull/110
